[Interface]
Address=10.200.0.2/24
PrivateKey=kGsQxmWza3Aoldza9gedrEBls27VuR8bWo6UiCkyqFw=

[Peer]
PublicKey=1V/ToSshIwyU3FLG5JJPU078elSTvbF2rHB/dTctjF4=
Endpoint=10.42.34.150
AllowedIPs=10.200.0.0/24
