table inet filter {
	chain input {
		type filter hook input priority 0; policy drop;

		ct state established,related accept
		iifname lo accept
		ip protocol udp udp dport 51820 accept
		ip protocol tcp ip saddr 10.200.0.2 dport 22 accept
		icmp type echo-request accept
	}

	chain output {
		type filter hook output priority 0; policy accept;
	}

	chain forward {
		type filter hook forward priority 0; policy drop;
	}
}

table ip nat {
	chain postrouting {
		type nat hook postrouting priority 100; policy accept;

		oifname "eth0" masquerade
	}
}
